theme: jekyll-theme-minimal

title: "DTN7"
# description: "Disruption-Tolerant Networking Implementations of the Bundle Protocol 7"

logo: assets/dtn7_logo.svg
show_downloads: false

# google_analytics: [Your Google Analytics tracking ID]

github:  
  repository_url: https://github.com/dtn7/
  repository_nwo: dtn7
